Add support for new Event Meters
laravel/cashier-stripe pull request #1698
Opened 2024-07-30 16:57 UTC by Bark-fa

Hello! This PR adds support for the new event meters by stripe for tracking usage in usage-based subscriptions, this is my first time contributing to cashier, and I've made every effort to maintain the style and naming conventions, and everything is fully typed, please let me know if I missed something either in the code itself or the tests.

Thank you so much for your time and effort.

2024-07-30 16:59 UTC, Bark-fa commented
I see the CI has failed but for some reason, I cannot see why, it shows a generic "blocked" message, is it some geo-restriction?

2024-07-30 17:43 UTC, Bark-fa commented
I managed to access it with a VPN, all style issues have been fixed

2024-08-01 13:11 UTC, driesvints commented
Can you remove all of your idea settings from this PR? Thanks!

2024-08-01 13:42 UTC, Bark-fa commented
Ah yes, sorry about that I thought they'd be in the .gitignore!

2024-08-01 14:08 UTC, Bark-fa commented
done @driesvints

2024-08-01 21:45 UTC, Bark-fa commented
@driesvints Do you need me to delete them from the previous commit history too?

2024-08-02 09:03 UTC, driesvints commented
@Bark-fa no that's okay. This PR will get squashed anyway.

2024-08-07 16:22 UTC, Bark-fa commented
Hello @driesvints, I'm reaching out because I noticed the PR is still in draft, I know you must be very busy, so if the PR needs any more work or if I missed anything in the docs please let me know and I'll gladly take it off your hands, I've got plenty of time this week.

Thanks!

2024-08-08 11:57 UTC, driesvints requested changes

2024-08-08 11:57 UTC, driesvints commented on src/Subscription.php
> +     * @throws ApiErrorException
```suggestion
     * @return \Stripe\MeterEvent
```

2024-08-08 11:57 UTC, driesvints commented on src/Subscription.php
> +     * @throws ApiErrorException
```suggestion
     * @return \Stripe\MeterEvent
```

2024-08-08 11:57 UTC, driesvints commented on src/Subscription.php
> +     * @throws ApiErrorException
```suggestion
     * @param  string|null  $price
     * @return \Illuminate\Support\Collection
```

2024-08-08 11:57 UTC, driesvints commented on src/SubscriptionItem.php
> +     * @throws ApiErrorException
```suggestion
     * @return \Stripe\MeterEvent
```

2024-08-08 11:57 UTC, driesvints commented on src/SubscriptionItem.php
> +     * @throws ApiErrorException
```suggestion
     * @return \Illuminate\Support\Collection
```

2024-08-08 11:57 UTC, driesvints commented on src/SubscriptionItem.php
> +     * @throws ApiErrorException
```suggestion
     * @return \Illuminate\Support\Collection
```

2024-08-08 14:20 UTC, driesvints commented
@Bark-fa sorry, needed a bit to have a thorough look here. I completely refactored all of this to be on a new trait on the billable. It's not needed for usage based billing to live closely to a subscription or subscription item. I've revised the API's and simplified things. 

The downside of this is that the written tests aren't applicable anymore. Could you rewrite those into a new `UsageBasedBillingTest.php` file? Then I believe this PR will be ready for review.

2024-08-08 15:46 UTC, Bark-fa commented
Done, I refactored the new tests into `UsageBasedBillingTest.php` and removed them from the old file.

Let me know if anything else comes up, thank you so much!

2024-08-08 18:04 UTC, Bark-fa commented
And regarding the new trait, I agree it's a better approach, I didn't allow myself the freedom to create new files though so I just wrote the functions where the old (now deprecated) code was 😅

2024-08-09 07:57 UTC, driesvints commented
Done. Thanks a bunch for this one @Bark-fa. Would also highly appreciate a PR to the docs!

2024-08-09 07:57 UTC, driesvints approved these changes

2024-08-09 16:58 UTC, Bark-fa commented
Hello @driesvints, you're very much welcome, I just submitted a [PR for the docs](https://github.com/laravel/docs/pull/9814)

2024-08-13 18:04 UTC, merged

2024-08-19 09:14 UTC, driesvints commented
@Bark-fa did you try these tests? Because they're failing atm.

2024-08-19 09:19 UTC, Bark-fa commented
Hello @driesvints, what tests specifically? I tried all the tests I wrote, and the old ones as well, and all ran with success, which ones are failing?

2024-08-19 09:39 UTC, driesvints commented
These: https://github.com/laravel/cashier-stripe/actions/runs/10444767851/job/28919710065

2024-08-19 10:15 UTC, Bark-fa commented
I just checked, I think the problem was caused by this line:
` $startTime = $options['start_time'] ?? $this->created_at->timestamp;`

This used to be in the Subscription class, so the logic was that if the user did not provide a start time, we'd set it to the date the subscription was created, but when it was moved to a trait, $this references the User model, this should fix it:
`        $startTime = $options['start_time'] ?? 1;`

I pushed it to my fork

2024-08-19 10:32 UTC, driesvints commented
Can you send in a PR? Thanks!

2024-08-19 10:33 UTC, Bark-fa commented
Of course, on it