[15.x] Catch missing payment intents
laravel/cashier-stripe pull request #1704
Opened 2024-08-12 20:17 UTC by shatterproof

This gracefully returns a not found exception instead of a 500 error when trying to access a non-existent or invalid payment intent ID in the browser such as from the route `/stripe/payment/xxx`.

2024-08-13 21:34 UTC, shatterproof commented
This was marked as a draft but should be ready to go, let me know if you need any changes @driesvints

2024-08-19 07:49 UTC, driesvints requested changes

2024-08-19 07:49 UTC, driesvints commented on src/Http/Controllers/PaymentController.php
> +            throw new NotFoundHttpException;
Can we convert this to an `abort(404, 'Payment not found');` instead?

2024-08-20 07:13 UTC, driesvints approved these changes
Thanks @shatterproof

2024-08-20 14:58 UTC, merged